package org.pojomatic.internal;

/**
 * A stub class to serve as a location for line numbers in byte-code generated by {@link PojomatorByteCodeGenerator}.
 * If you are looking at this class, the odds are that you have encountered an stack trace including a line which
 * is allegedly from this class. The actual code was generated by {@code PojomatorByteCodeGenerator}; you can look for
 * occurrences of {@code visitLineNumber} in that class to determine what byte code was likely corresponding to
 * the stack trace element.
 */
public final class PojomatorStub {
  private PojomatorStub() {}
}
